dist: trusty
sudo: false
language: cpp

compiler:
  - gcc
  - clang

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
      - cmake
      - gettext
      - bison
      - pkg-config
      - gperf
      - ruby-full
      - rake
      - libglew-dev
      - libpng-dev
      - libpcre3-dev
      - libxml++2.6-dev
      - libfreetype6-dev
      - libdevil-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-thread-dev
      - libglew-dev
      - libglm-dev
      - libglfw-dev  # For CEGUI
      - libopenal1

before_script:
  - git submodule update --init --recursive
  - curl -Lo ninja-linux.zip "https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip"
  - unzip ninja-linux.zip
  - export PATH=$PATH:$PWD

script:
  - ./travis.sh
