language: cpp

compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "add-here-inside-quotes"

addons:
  coverity_scan:
    project:
      name: "Secretchronicles/TSC"
      description: "Build submitted via Travis CI"
    notification_email: email@address.here
    build_command_prepend: "mkdir tsc/build && cd tsc/build && cmake .."
    build_command:   "make"
    branch_pattern: coverity_scan

notifications:
  email:
    on_success: change
    on_failure: change

before_install:
  # new boost packages (1.54 and 1.55)
  - sudo add-apt-repository -y ppa:boost-latest/ppa
  # new cmake (2.8.7 -> 2.18.11)
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo apt-get update -qq

install:
  - >
   sudo apt-get install -qq cmake gettext bison pkg-config gperf
   libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev
   ruby-full rake libglew-dev libpng-dev libpcre3-dev libxml++2.6-dev
   libfreetype6-dev libdevil-dev libboost-filesystem1.54-dev libboost-chrono1.54-dev
   libboost-thread1.54-dev

before_script:
    # pull all sub modules recursively
  - git submodule update --init --recursive
    # ubuntu precise does not ship a pkg-config file, fall back to FindXXX.cmake module
  - sed 's|pkg_check_modules(SDL_TTF REQUIRED SDL_ttf)|find_package(SDL_ttf REQUIRED)|' -i tsc/CMakeLists.txt

script:
  - mkdir tsc/build && cd tsc/build && cmake .. && make
