dist: trusty
sudo: false
language: cpp

compiler:
  - gcc
  - clang

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  apt:
    packages:
      - cmake
      - gettext
      - bison
      - pkg-config
      - gperf
      - libsfml-dev
      - ruby-full
      - rake
      - libglew-dev
      - libpng-dev
      - libpcre3-dev
      - libxml++2.6-dev
      - libfreetype6-dev
      - libdevil-dev
      - libboost-filesystem-dev
      - libboost-chrono-dev
      - libboost-thread-dev
      - ninja

before_script:
    # pull all sub modules recursively
  - git submodule update --init --recursive

script:
  - mkdir build && cd build && cmake -G Ninja ../tsc && ninja
